project_id = "sarkari-result"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3001", "http://localhost:3001/admin"]
jwt_expiry = 3600
enable_signup = false

[storage]
file_size_limit = "50MiB"
